name: mobile1_flutter_coding_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lint: ^2.6.2
  shared_preferences: ^2.5.3
  encrypt: ^5.0.3
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  go_router: ^15.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  flutter_hooks: ^0.21.2
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.7.0

flutter:

  uses-material-design: true
